#import "../../templates/template-report.typ": *

#show: template-report.with(
  title: "Week 5 Report",
  student_id: "2023-12675",
  author: "박지호",
)

This report is on the article _AI: Dystopia or Utopia?_, an article by Vinod Khosla sharing their insights on the future AI may bring. The article opens by emphasizing the revolutionary nature of AI, comparing its impact to that of engine for physical labor. The author then argues that fears about the dystopian future about AI are mostly unfounded, claiming that the most realistic dystopia would happen if the West were to lose to China in the AI race. According to them, potential job losses can be dealt with smart interventions from the government, and in the long run AI will generate enough wealth for everyone. Issues of social control and manipulation can be prevented with some type of legislation. While some concern that AI may make incorrect decisions due to potential bias, author claims that these bias originate from humans, and AI can, in fact, help correct it. Also, on the contrary to popular belief that AI may diminish human creativity and critical thinking, AI can help untalented people express their creativity in a way they couldn't before.

While I agree with few of the points the author mentioned, their perspective on the matter feels overly optimisitc. Some of the solutions they proposed seem to boil down to "democracy can solve it", and felt too abstract to be considered seriously. Furthermore, as far as I am aware, the level of fine grained control the author provided as solutions for these problems is not even possible at the current state of technology. Also, I found the America-centric point of view present throughout this mildly disturbing.

I do not believe that AI will bring about the dystopian future some say it will. I also do not believe that we should stop developing AI. However, the risks definitely exist, and shouldn't be dismissed so easily. The authors tone almost suggests that we should disregard these supposedly small risks and focus on outpacing "our enemies". I believe this to be the most dangerous mindset. The author says AI is different from nuclear bombs, which, I agree, but this is the _exact_ mindset that lead to its invention, the most horrible, inhumane invention known to mankind. This is the recipe for disaster.

The author then points out the benefits AI can provide. First, the AI will be able to perform tasks currently handled by humans, leading to increased efficiency and productivity. IT would also help us physically in multitude of ways. AI would also improve the healthcare system immensely, with personalized care and better cures. Personalized, near-free tutors enabled by AI will also improve education. AI can also assist in science, technology, other fields, as well as support better decision making in general. The author then shares couple insight on how the concepts we know now may alter over the course of next few years because of AI. First, capitalism may evolve in a way that eliminates few of its undesirable side-effects, as the economic growth and abundance of resource would make this possible. Massive shifts of professions will happen, and in a pace more rapid than ever.

I agree that most of his visions definitely reside within the realm of possibility. However, we should avoid personifying, or _deifying_ AI as much. We should treat AI as what it is, a machine that predicts most plausible output for a given input, based on numerous known pairs of input and output. The efficiency and generality of this methodology allows it to be applied in variety of fields, greatly enhancing productivity. However, that is only a natural outcome of utilizing a better tool. While it would make sense to say AI will bring utopia since this increased productivity will lead to a better world, this statement can be misleading as it portrays AI as some kind of benevolent force.

However, like I just said, that's not what AI is, it is nothing more than a very effective tool. Therefore, it won't fundamentally change the human nature. I don't believe that humans are inherently terrible, but we are not exceptionally virtuous either. Thanks to agricultural and industrial revolution, there are definitely more than enough food to feed everyone in this world currently, but in some part of the world, people still starve to death. Although AI is an effective tool for solving many problems, and the effectiveness of these solutions may in turn solve some other problems as a side effect, but it wouldn't automatically solve every problem in the world like the author is seemingly suggesting.